id = "ir-black"
name = "IR Black"
version = "0.0.1"
schema_version = 1
authors = ["Samet Aylak <sametaylak29@gmail.com>"]
description = "IR Black theme"
repository = "https://github.com/sametaylak/ir-black-zed-theme"
